stages: 
    - test
    - build
    - deploy
unit-test: 
    stage: test
    script: 
        - 'd: cd "D:\Program Files\Unity\Editor\" -batchmode -projectPath D:\GitHub\testing -runTests -testPlatform editmode -logfile - -testResults ./unit-tests.xml | Out-Default'
    tags: 
        - unity

unity-build:
    stage: build
    script: "echo 'Building...'"
    tags:
        - unity

playstore:
    stage: deploy
    script: "echo 'Deploying...'"
    tags:
        - unity